### ISSUE TITLE
Add some infos

### ISSUE THREAD

**Issue by GerhardKreuzer** [Trikos/Home-Assistant-Naming-Convention#1]
Hi,
you used 'domain' here, but you never explained what can typed in here, or if this is given by HA.
Only in the samples you used specific values. Where did they come from. Can I add this values some where in HA or have I use a fixed preset?

Maybe you can be more specific at that point. Thanks.

Rest of the document is very helpful for beginners. Cheers.

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
Hi,
found out, that my temp sensor from SwissBot schows the domain name 'sensor' and I am not allowed to change this. 
Is there a chance to define domains? If not, where can I get a list of domain names and who decide which domain name is used for a device or device function?

With best regards

Gerhard

**Comment by Trikos** [comment]
> Hi, you used 'domain' here, but you never explained what can typed in here, or if this is given by HA. Only in the samples you used specific values. Where did they come from. Can I add this values some where in HA or have I use a fixed preset?
> 
> Maybe you can be more specific at that point. Thanks.
> 
> Rest of the document is very helpful for beginners. Cheers.
> 
> With best regards
> 
> Gerhard

Hi, thanks for reading my doc. Im adding a descriptions for domains

> Hi, found out, that my temp sensor from SwissBot schows the domain name 'sensor' and I am not allowed to change this. Is there a chance to define domains? If not, where can I get a list of domain names and who decide which domain name is used for a device or device function?
> 
> With best regards
> 
> Gerhard

You can find a list of domain using template in home assistant and copy pasting the code written by `bacco007` [here](https://community.home-assistant.io/t/list-of-all-domains-entities/148059/3?u=nicolo_bartolomei)
