### ISSUE TITLE
Rules for entity-ID

### ISSUE THREAD

**Issue by GerhardKreuzer** [Trikos/Home-Assistant-Naming-Convention#2]
Hi,
some more infos about Entity_ID:
If you want to keep this names short, you could have the idea to use 'camel' type names for better reading: tempMeter or btSignal ...

But entity-IDs must have only lower case characters!!!!!! Please note this some where in your document.

You get the super info 'Entity-ID wrong', no info what wents wrong it took time to find the lower case (shit) out.

For newbees it would be very fine to know such things in advance and maybe someone cames along with ideas to have short AND readable names.

Thanks a lot.

With best regards

Gerhard

**Comment by Trikos** [comment]
Hi, the doc has been improved with your tips :)

Thanks for report it
